DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  outCome TEXT NOT NULL,
  bestOf TEXT NOT NULL,
  enemy TEXT NOT NULL,
  score TEXT NOT NULL,
  league TEXT NOT NULL,
  mapOne TEXT NOT NULL,
  mapTwo TEXT,
  mapThree TEXT,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
