DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS upcoming;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE result (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  outCome TEXT NOT NULL,
  bestOf TEXT NOT NULL,
  enemy TEXT NOT NULL,
  score TEXT NOT NULL,
  league TEXT NOT NULL,
  mapOne TEXT NOT NULL,
  mapTwo TEXT,
  mapThree TEXT,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE upcoming (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upcoming_match_day TEXT NOT NULL,
  upcoming_startTime TEXT NOT NULL,
  upcoming_enemy TEXT NOT NULL,
  upcoming_league TEXT NOT NULL,
  upcoming_bestOf TEXT NOT NULL,
  upcoming_stage TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
